#!/bin/busybox ash
#
# /usr/sbin/rebuildfstab
#
#   2023-02-14 Changed by Alphons van der Heijden (speeds up dramatically)
#
PATH="/bin:/sbin:/usr/bin:/usr/sbin"
export PATH
umask 022

# Exit if script is already running
[ -e /proc/partitions ] || exit
if [ -e /var/run/rebuildfstab.pid ]; then
 if [ -e "/proc/$(cat /var/run/rebuildfstab.pid)" ]; then
  touch /var/run/rebuildfstab.rescan 2>/dev/null
  exit
 fi
 rm -f /var/run/rebuildfstab.pid
fi
echo "$$" >/var/run/rebuildfstab.pid

TMP="/tmp/fstab.$$.tmp"
ADDEDBY="# Added by TC"
DEVROOT="/dev"

# Read a list of CDROM/DVD Drives
CDROMS=""
CDROMSF=/etc/sysconfig/cdroms
[ -s "$CDROMSF" ] &&  CDROMS=`cat "$CDROMSF"`

grep -v "$ADDEDBY" /etc/fstab > "$TMP"

NTFSDRIVER=""
checkntfs() {
    if [ -z "$NTFSDRIVER" ]; then
        if [ -f /usr/bin/ntfs-3g ] || [ -f /usr/local/bin/ntfs-3g ] || [ -f /bin/ntfs-3g ]; then
            NTFSDRIVER="ntfs-3g"
        else
            NTFSDRIVER="ntfs3"
        fi
    fi

    FSTYPE="$NTFSDRIVER"
    case "$FSTYPE" in
        ntfs3|ntfs-3g) OPTIONS="$OPTIONS",iocharset=utf8;  ;;
        ntfs) OPTIONS="$OPTIONS,ro,umask=000";  ;;
    esac
}

# Loop through block devices
IFS=$'\n'
for device in $(blkid | grep -v 'zram\|loop'); do
  BLOCKDEV=$(echo $device | cut -d: -f1)
  FSTYPE=$(echo $device | awk -F'TYPE="' '{ print $2 }' | awk -F'"' '{ print $1}')
  DEVNAME=$(echo $BLOCKDEV | sed 's/.*\///')
  case "$CDROMS" in *"$BLOCKDEV"*) FSTYPE="auto" ;; esac
  case "$FSTYPE" in linux_raid_member|LVM2_member|zfs_member) continue;  ;; esac
  if [ -z "$FSTYPE" ]; then
    DEVMAJOR="$(cat /sys/class/block/$DEVNAME/dev |cut -f1 -d:)"
    case "$DEVMAJOR" in
      2|98) FSTYPE="auto";  ;;
      *) continue;  ;;
    esac
  fi
  MOUNTPOINT="/mnt/$DEVNAME"
  OPTIONS="noauto,users,exec"
  case "$FSTYPE" in
    ntfs) checkntfs ;;
    vfat|msdos) OPTIONS="${OPTIONS},umask=000" ;;
    ext2|ext3|ext4) OPTIONS="${OPTIONS},relatime" ;;
    swap) OPTIONS="defaults"; MOUNTPOINT="none" ;;
  esac
  if [ "$MOUNTPOINT" != "none" ]; then
    mkdir -p "/mnt/$DEVNAME" >/dev/null 2>&1
  fi
  printf "%-15s %-15s %-8s %-20s %-s\n" "$DEVROOT/$DEVNAME" "$MOUNTPOINT" "$FSTYPE" "$OPTIONS" "0 0 $ADDEDBY" >> "$TMP"
done

# Clean up
mv "$TMP" /etc/fstab
rm -f /var/run/rebuildfstab.pid
sync

# If another copy tried to run while we were running, rescan.
if [ -e /var/run/rebuildfstab.rescan ]; then
  rm -f /var/run/rebuildfstab.rescan
  exec $0 "$@"
fi
